<?php
return array (
  13 => 
  array (
    'catid' => '13',
    'parentid' => '0',
    'catname' => '集团事业',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=13&siteid=1',
    'status' => '1',
  ),
  104 => 
  array (
    'catid' => '104',
    'parentid' => '0',
    'catname' => '集团党建',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=104&siteid=1',
    'status' => '1',
  ),
  91 => 
  array (
    'catid' => '91',
    'parentid' => '0',
    'catname' => '集团新闻',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=91&siteid=1',
    'status' => '1',
  ),
  164 => 
  array (
    'catid' => '164',
    'parentid' => '96',
    'catname' => '企业文化',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=164&siteid=1',
    'status' => '1',
  ),
  144 => 
  array (
    'catid' => '144',
    'parentid' => '0',
    'catname' => '人力资源',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=144&siteid=1',
    'status' => '1',
  ),
  57 => 
  array (
    'catid' => '57',
    'parentid' => '252',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=57&siteid=1',
    'status' => '1',
  ),
  82 => 
  array (
    'catid' => '82',
    'parentid' => '13',
    'catname' => '青年创业管理咨询有限公司',
    'siteid' => '1',
    'listorder' => '15',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=82&siteid=1',
    'status' => '1',
  ),
  58 => 
  array (
    'catid' => '58',
    'parentid' => '252',
    'catname' => '集团简介',
    'siteid' => '1',
    'listorder' => '58',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=58&siteid=1',
    'status' => '1',
  ),
  163 => 
  array (
    'catid' => '163',
    'parentid' => '112',
    'catname' => '业务介绍',
    'siteid' => '1',
    'listorder' => '65',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=163&siteid=1',
    'status' => '1',
  ),
  78 => 
  array (
    'catid' => '78',
    'parentid' => '112',
    'catname' => '项目业绩',
    'siteid' => '1',
    'listorder' => '66',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=78&siteid=1',
    'status' => '1',
  ),
  66 => 
  array (
    'catid' => '66',
    'parentid' => '112',
    'catname' => '团队风采',
    'siteid' => '1',
    'listorder' => '66',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=66&siteid=1',
    'status' => '1',
  ),
  63 => 
  array (
    'catid' => '63',
    'parentid' => '112',
    'catname' => '招标公告',
    'siteid' => '1',
    'listorder' => '67',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=63&siteid=1',
    'status' => '1',
  ),
  79 => 
  array (
    'catid' => '79',
    'parentid' => '112',
    'catname' => '中标公示',
    'siteid' => '1',
    'listorder' => '68',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=79&siteid=1',
    'status' => '1',
  ),
  178 => 
  array (
    'catid' => '178',
    'parentid' => '112',
    'catname' => '公司资质',
    'siteid' => '1',
    'listorder' => '69',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=178&siteid=1',
    'status' => '1',
  ),
  87 => 
  array (
    'catid' => '87',
    'parentid' => '82',
    'catname' => '团队风采',
    'siteid' => '1',
    'listorder' => '87',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=87&siteid=1',
    'status' => '1',
  ),
  88 => 
  array (
    'catid' => '88',
    'parentid' => '82',
    'catname' => '新闻动态',
    'siteid' => '1',
    'listorder' => '88',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=88&siteid=1',
    'status' => '1',
  ),
  96 => 
  array (
    'catid' => '96',
    'parentid' => '0',
    'catname' => '集团概况',
    'siteid' => '1',
    'listorder' => '96',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=96&siteid=1',
    'status' => '1',
  ),
  103 => 
  array (
    'catid' => '103',
    'parentid' => '82',
    'catname' => '业务范畴',
    'siteid' => '1',
    'listorder' => '103',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=103&siteid=1',
    'status' => '1',
  ),
  121 => 
  array (
    'catid' => '121',
    'parentid' => '114',
    'catname' => '资质展示',
    'siteid' => '1',
    'listorder' => '121',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=121&siteid=1',
    'status' => '1',
  ),
  265 => 
  array (
    'catid' => '265',
    'parentid' => '114',
    'catname' => '业务介绍',
    'siteid' => '1',
    'listorder' => '122',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=265&siteid=1',
    'status' => '1',
  ),
  230 => 
  array (
    'catid' => '230',
    'parentid' => '114',
    'catname' => '招标公告',
    'siteid' => '1',
    'listorder' => '125',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=230&siteid=1',
    'status' => '1',
  ),
  231 => 
  array (
    'catid' => '231',
    'parentid' => '114',
    'catname' => '中标公示',
    'siteid' => '1',
    'listorder' => '126',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=231&siteid=1',
    'status' => '1',
  ),
  155 => 
  array (
    'catid' => '155',
    'parentid' => '144',
    'catname' => '人才招聘',
    'siteid' => '1',
    'listorder' => '154',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=155&siteid=1',
    'status' => '1',
  ),
  154 => 
  array (
    'catid' => '154',
    'parentid' => '144',
    'catname' => '人才培养',
    'siteid' => '1',
    'listorder' => '155',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=154&siteid=1',
    'status' => '1',
  ),
  169 => 
  array (
    'catid' => '169',
    'parentid' => '93',
    'catname' => '合作伙伴',
    'siteid' => '1',
    'listorder' => '169',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=169&siteid=1',
    'status' => '1',
  ),
  243 => 
  array (
    'catid' => '243',
    'parentid' => '187',
    'catname' => '业务范畴',
    'siteid' => '1',
    'listorder' => '189',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=243&siteid=1',
    'status' => '1',
  ),
  193 => 
  array (
    'catid' => '193',
    'parentid' => '191',
    'catname' => '团队风采',
    'siteid' => '1',
    'listorder' => '193',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=193&siteid=1',
    'status' => '1',
  ),
  194 => 
  array (
    'catid' => '194',
    'parentid' => '191',
    'catname' => '新闻动态',
    'siteid' => '1',
    'listorder' => '194',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=194&siteid=1',
    'status' => '1',
  ),
  196 => 
  array (
    'catid' => '196',
    'parentid' => '191',
    'catname' => '资质展示',
    'siteid' => '1',
    'listorder' => '196',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=196&siteid=1',
    'status' => '1',
  ),
  206 => 
  array (
    'catid' => '206',
    'parentid' => '104',
    'catname' => '青春党建',
    'siteid' => '1',
    'listorder' => '206',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=206&siteid=1',
    'status' => '1',
  ),
  207 => 
  array (
    'catid' => '207',
    'parentid' => '104',
    'catname' => '共青团委',
    'siteid' => '1',
    'listorder' => '207',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=207&siteid=1',
    'status' => '1',
  ),
  208 => 
  array (
    'catid' => '208',
    'parentid' => '104',
    'catname' => '工      会',
    'siteid' => '1',
    'listorder' => '208',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=208&siteid=1',
    'status' => '1',
  ),
  209 => 
  array (
    'catid' => '209',
    'parentid' => '104',
    'catname' => '妇  委  会',
    'siteid' => '1',
    'listorder' => '209',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=209&siteid=1',
    'status' => '1',
  ),
  223 => 
  array (
    'catid' => '223',
    'parentid' => '78',
    'catname' => '招标代理业绩',
    'siteid' => '1',
    'listorder' => '223',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=223&siteid=1',
    'status' => '1',
  ),
  224 => 
  array (
    'catid' => '224',
    'parentid' => '78',
    'catname' => '政府采购业绩',
    'siteid' => '1',
    'listorder' => '224',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=224&siteid=1',
    'status' => '1',
  ),
  225 => 
  array (
    'catid' => '225',
    'parentid' => '78',
    'catname' => '造价咨询业绩',
    'siteid' => '1',
    'listorder' => '225',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=225&siteid=1',
    'status' => '1',
  ),
  226 => 
  array (
    'catid' => '226',
    'parentid' => '78',
    'catname' => '项目管理业绩',
    'siteid' => '1',
    'listorder' => '226',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=226&siteid=1',
    'status' => '1',
  ),
  227 => 
  array (
    'catid' => '227',
    'parentid' => '78',
    'catname' => '建筑设计业绩',
    'siteid' => '1',
    'listorder' => '227',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=227&siteid=1',
    'status' => '1',
  ),
  228 => 
  array (
    'catid' => '228',
    'parentid' => '78',
    'catname' => '室内设计业绩',
    'siteid' => '1',
    'listorder' => '228',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=228&siteid=1',
    'status' => '1',
  ),
  234 => 
  array (
    'catid' => '234',
    'parentid' => '206',
    'catname' => '支部简介',
    'siteid' => '1',
    'listorder' => '234',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=234&siteid=1',
    'status' => '1',
  ),
  235 => 
  array (
    'catid' => '235',
    'parentid' => '206',
    'catname' => '一个思想',
    'siteid' => '1',
    'listorder' => '235',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=235&siteid=1',
    'status' => '1',
  ),
  236 => 
  array (
    'catid' => '236',
    'parentid' => '206',
    'catname' => '三个内涵',
    'siteid' => '1',
    'listorder' => '236',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=236&siteid=1',
    'status' => '1',
  ),
  237 => 
  array (
    'catid' => '237',
    'parentid' => '206',
    'catname' => '一个核心',
    'siteid' => '1',
    'listorder' => '237',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=237&siteid=1',
    'status' => '1',
  ),
  238 => 
  array (
    'catid' => '238',
    'parentid' => '206',
    'catname' => '六个内容',
    'siteid' => '1',
    'listorder' => '238',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=238&siteid=1',
    'status' => '1',
  ),
  239 => 
  array (
    'catid' => '239',
    'parentid' => '206',
    'catname' => '组织建设',
    'siteid' => '1',
    'listorder' => '239',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=239&siteid=1',
    'status' => '1',
  ),
  240 => 
  array (
    'catid' => '240',
    'parentid' => '207',
    'catname' => '青年●担当',
    'siteid' => '1',
    'listorder' => '240',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=240&siteid=1',
    'status' => '1',
  ),
  241 => 
  array (
    'catid' => '241',
    'parentid' => '208',
    'catname' => '职工●当家',
    'siteid' => '1',
    'listorder' => '241',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=241&siteid=1',
    'status' => '1',
  ),
  242 => 
  array (
    'catid' => '242',
    'parentid' => '209',
    'catname' => '女性●力量',
    'siteid' => '1',
    'listorder' => '242',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=242&siteid=1',
    'status' => '1',
  ),
  245 => 
  array (
    'catid' => '245',
    'parentid' => '116',
    'catname' => '资质展示',
    'siteid' => '1',
    'listorder' => '245',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=245&siteid=1',
    'status' => '1',
  ),
  249 => 
  array (
    'catid' => '249',
    'parentid' => '116',
    'catname' => '团队风采',
    'siteid' => '1',
    'listorder' => '249',
    'type' => '0',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=lists&catid=249&siteid=1',
    'status' => '1',
  ),
);
?>