<?php
return array (
  97 => 
  array (
    'catid' => '97',
    'parentid' => '96',
    'catname' => '公司简介',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=97&siteid=1',
    'status' => '1',
  ),
  99 => 
  array (
    'catid' => '99',
    'parentid' => '96',
    'catname' => '组织架构',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=99&siteid=1',
    'status' => '1',
  ),
  143 => 
  array (
    'catid' => '143',
    'parentid' => '96',
    'catname' => '成长历程',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=143&siteid=1',
    'status' => '1',
  ),
  191 => 
  array (
    'catid' => '191',
    'parentid' => '13',
    'catname' => '春禾绿科农业发展有限公司',
    'siteid' => '1',
    'listorder' => '6',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=191&siteid=1',
    'status' => '1',
  ),
  112 => 
  array (
    'catid' => '112',
    'parentid' => '13',
    'catname' => '中信蓝海项目管理有限公司',
    'siteid' => '1',
    'listorder' => '11',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=112&siteid=1',
    'status' => '1',
  ),
  114 => 
  array (
    'catid' => '114',
    'parentid' => '13',
    'catname' => '重咨集团（陕西）有限公司',
    'siteid' => '1',
    'listorder' => '12',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=114&siteid=1',
    'status' => '1',
  ),
  116 => 
  array (
    'catid' => '116',
    'parentid' => '13',
    'catname' => '同乘设计（陕西）有限公司',
    'siteid' => '1',
    'listorder' => '13',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=116&siteid=1',
    'status' => '1',
  ),
  187 => 
  array (
    'catid' => '187',
    'parentid' => '13',
    'catname' => '绿   草   地园林绿化有限公司',
    'siteid' => '1',
    'listorder' => '14',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=187&siteid=1',
    'status' => '1',
  ),
  115 => 
  array (
    'catid' => '115',
    'parentid' => '112',
    'catname' => '区域公司',
    'siteid' => '1',
    'listorder' => '63',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=115&siteid=1',
    'status' => '1',
  ),
  81 => 
  array (
    'catid' => '81',
    'parentid' => '112',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '71',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=81&siteid=1',
    'status' => '1',
  ),
  83 => 
  array (
    'catid' => '83',
    'parentid' => '82',
    'catname' => '公司简介',
    'siteid' => '1',
    'listorder' => '83',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=83&siteid=1',
    'status' => '1',
  ),
  93 => 
  array (
    'catid' => '93',
    'parentid' => '0',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '93',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=93&siteid=1',
    'status' => '1',
  ),
  119 => 
  array (
    'catid' => '119',
    'parentid' => '115',
    'catname' => '榆林区域公司',
    'siteid' => '1',
    'listorder' => '117',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=119&siteid=1',
    'status' => '1',
  ),
  118 => 
  array (
    'catid' => '118',
    'parentid' => '115',
    'catname' => '延安区域公司',
    'siteid' => '1',
    'listorder' => '118',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=118&siteid=1',
    'status' => '1',
  ),
  117 => 
  array (
    'catid' => '117',
    'parentid' => '115',
    'catname' => '西安区域公司',
    'siteid' => '1',
    'listorder' => '119',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=117&siteid=1',
    'status' => '1',
  ),
  120 => 
  array (
    'catid' => '120',
    'parentid' => '114',
    'catname' => '公司简介',
    'siteid' => '1',
    'listorder' => '120',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=120&siteid=1',
    'status' => '1',
  ),
  122 => 
  array (
    'catid' => '122',
    'parentid' => '114',
    'catname' => '业务介绍',
    'siteid' => '1',
    'listorder' => '122',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=122&siteid=1',
    'status' => '1',
  ),
  128 => 
  array (
    'catid' => '128',
    'parentid' => '114',
    'catname' => '项目业绩',
    'siteid' => '1',
    'listorder' => '124',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=128&siteid=1',
    'status' => '1',
  ),
  127 => 
  array (
    'catid' => '127',
    'parentid' => '114',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '127',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=127&siteid=1',
    'status' => '1',
  ),
  129 => 
  array (
    'catid' => '129',
    'parentid' => '128',
    'catname' => '招标代理',
    'siteid' => '1',
    'listorder' => '129',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=129&siteid=1',
    'status' => '1',
  ),
  130 => 
  array (
    'catid' => '130',
    'parentid' => '128',
    'catname' => '政府采购',
    'siteid' => '1',
    'listorder' => '130',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=130&siteid=1',
    'status' => '1',
  ),
  131 => 
  array (
    'catid' => '131',
    'parentid' => '128',
    'catname' => '投资咨询',
    'siteid' => '1',
    'listorder' => '131',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=131&siteid=1',
    'status' => '1',
  ),
  132 => 
  array (
    'catid' => '132',
    'parentid' => '128',
    'catname' => '规划咨询',
    'siteid' => '1',
    'listorder' => '132',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=132&siteid=1',
    'status' => '1',
  ),
  133 => 
  array (
    'catid' => '133',
    'parentid' => '128',
    'catname' => '决策咨询',
    'siteid' => '1',
    'listorder' => '133',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=133&siteid=1',
    'status' => '1',
  ),
  134 => 
  array (
    'catid' => '134',
    'parentid' => '128',
    'catname' => '低碳咨询',
    'siteid' => '1',
    'listorder' => '134',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=134&siteid=1',
    'status' => '1',
  ),
  135 => 
  array (
    'catid' => '135',
    'parentid' => '128',
    'catname' => '节能咨询',
    'siteid' => '1',
    'listorder' => '135',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=135&siteid=1',
    'status' => '1',
  ),
  136 => 
  array (
    'catid' => '136',
    'parentid' => '128',
    'catname' => '风评咨询',
    'siteid' => '1',
    'listorder' => '136',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=136&siteid=1',
    'status' => '1',
  ),
  141 => 
  array (
    'catid' => '141',
    'parentid' => '128',
    'catname' => '工程造价',
    'siteid' => '1',
    'listorder' => '137',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=141&siteid=1',
    'status' => '1',
  ),
  138 => 
  array (
    'catid' => '138',
    'parentid' => '128',
    'catname' => '项目管理',
    'siteid' => '1',
    'listorder' => '138',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=138&siteid=1',
    'status' => '1',
  ),
  139 => 
  array (
    'catid' => '139',
    'parentid' => '128',
    'catname' => '环境影响评价',
    'siteid' => '1',
    'listorder' => '139',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=139&siteid=1',
    'status' => '1',
  ),
  140 => 
  array (
    'catid' => '140',
    'parentid' => '128',
    'catname' => '投融资服务',
    'siteid' => '1',
    'listorder' => '140',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=140&siteid=1',
    'status' => '1',
  ),
  150 => 
  array (
    'catid' => '150',
    'parentid' => '82',
    'catname' => '资质展示',
    'siteid' => '1',
    'listorder' => '150',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=150&siteid=1',
    'status' => '1',
  ),
  89 => 
  array (
    'catid' => '89',
    'parentid' => '82',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '151',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=89&siteid=1',
    'status' => '1',
  ),
  158 => 
  array (
    'catid' => '158',
    'parentid' => '93',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '158',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=158&siteid=1',
    'status' => '1',
  ),
  159 => 
  array (
    'catid' => '159',
    'parentid' => '93',
    'catname' => '友情链接',
    'siteid' => '1',
    'listorder' => '159',
    'type' => '1',
    'url' => 'http://zhingxinlh.d152.ptzygj.com/index.php?m=mobile&a=page&catid=159&siteid=1',
    'status' => '1',
  ),
  160 => 
  array (
    'catid' => '160',
    'parentid' => '93',
    'catname' => '合作伙伴',
    'siteid' => '1',
    'listorder' => '160',
    'type' => '1',
    'url' => 'http://zhingxinlh.d152.ptzygj.com/index.php?m=mobile&a=page&catid=160&siteid=1',
    'status' => '1',
  ),
  161 => 
  array (
    'catid' => '161',
    'parentid' => '128',
    'catname' => '教育培训',
    'siteid' => '1',
    'listorder' => '161',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=161&siteid=1',
    'status' => '1',
  ),
  162 => 
  array (
    'catid' => '162',
    'parentid' => '128',
    'catname' => 'PPT 项目中心',
    'siteid' => '1',
    'listorder' => '162',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=162&siteid=1',
    'status' => '1',
  ),
  188 => 
  array (
    'catid' => '188',
    'parentid' => '187',
    'catname' => '公司简介',
    'siteid' => '1',
    'listorder' => '188',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=188&siteid=1',
    'status' => '1',
  ),
  190 => 
  array (
    'catid' => '190',
    'parentid' => '187',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '190',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=190&siteid=1',
    'status' => '1',
  ),
  192 => 
  array (
    'catid' => '192',
    'parentid' => '191',
    'catname' => '企业简介',
    'siteid' => '1',
    'listorder' => '192',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=192&siteid=1',
    'status' => '1',
  ),
  195 => 
  array (
    'catid' => '195',
    'parentid' => '191',
    'catname' => '项目介绍',
    'siteid' => '1',
    'listorder' => '195',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=195&siteid=1',
    'status' => '1',
  ),
  197 => 
  array (
    'catid' => '197',
    'parentid' => '191',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '197',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=197&siteid=1',
    'status' => '1',
  ),
  214 => 
  array (
    'catid' => '214',
    'parentid' => '207',
    'catname' => '团委简介 ',
    'siteid' => '1',
    'listorder' => '214',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=214&siteid=1',
    'status' => '1',
  ),
  217 => 
  array (
    'catid' => '217',
    'parentid' => '208',
    'catname' => '工会简介',
    'siteid' => '1',
    'listorder' => '217',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=217&siteid=1',
    'status' => '1',
  ),
  220 => 
  array (
    'catid' => '220',
    'parentid' => '209',
    'catname' => '妇委会简介',
    'siteid' => '1',
    'listorder' => '220',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=220&siteid=1',
    'status' => '1',
  ),
  244 => 
  array (
    'catid' => '244',
    'parentid' => '116',
    'catname' => '公司简介',
    'siteid' => '1',
    'listorder' => '244',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=244&siteid=1',
    'status' => '1',
  ),
  246 => 
  array (
    'catid' => '246',
    'parentid' => '116',
    'catname' => '业务介绍',
    'siteid' => '1',
    'listorder' => '246',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=246&siteid=1',
    'status' => '1',
  ),
  247 => 
  array (
    'catid' => '247',
    'parentid' => '116',
    'catname' => '项目业绩',
    'siteid' => '1',
    'listorder' => '247',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=247&siteid=1',
    'status' => '1',
  ),
  248 => 
  array (
    'catid' => '248',
    'parentid' => '116',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '248',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=248&siteid=1',
    'status' => '1',
  ),
  250 => 
  array (
    'catid' => '250',
    'parentid' => '247',
    'catname' => '子栏目1',
    'siteid' => '1',
    'listorder' => '250',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=250&siteid=1',
    'status' => '1',
  ),
  251 => 
  array (
    'catid' => '251',
    'parentid' => '247',
    'catname' => '子栏目2',
    'siteid' => '1',
    'listorder' => '251',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=251&siteid=1',
    'status' => '1',
  ),
  252 => 
  array (
    'catid' => '252',
    'parentid' => '0',
    'catname' => 'mobile',
    'siteid' => '1',
    'listorder' => '252',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=252&siteid=1',
    'status' => '1',
  ),
  253 => 
  array (
    'catid' => '253',
    'parentid' => '252',
    'catname' => '企业文化',
    'siteid' => '1',
    'listorder' => '253',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=253&siteid=1',
    'status' => '1',
  ),
  254 => 
  array (
    'catid' => '254',
    'parentid' => '252',
    'catname' => '中信蓝海联系',
    'siteid' => '1',
    'listorder' => '254',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=254&siteid=1',
    'status' => '1',
  ),
  255 => 
  array (
    'catid' => '255',
    'parentid' => '252',
    'catname' => '重咨集团联系',
    'siteid' => '1',
    'listorder' => '255',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=255&siteid=1',
    'status' => '1',
  ),
  256 => 
  array (
    'catid' => '256',
    'parentid' => '252',
    'catname' => '同乘设计联系',
    'siteid' => '1',
    'listorder' => '256',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=256&siteid=1',
    'status' => '1',
  ),
  257 => 
  array (
    'catid' => '257',
    'parentid' => '252',
    'catname' => '绿草地联系',
    'siteid' => '1',
    'listorder' => '257',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=257&siteid=1',
    'status' => '1',
  ),
  258 => 
  array (
    'catid' => '258',
    'parentid' => '252',
    'catname' => '春禾绿科联系',
    'siteid' => '1',
    'listorder' => '258',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=258&siteid=1',
    'status' => '1',
  ),
  259 => 
  array (
    'catid' => '259',
    'parentid' => '252',
    'catname' => '青年创业联系',
    'siteid' => '1',
    'listorder' => '259',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=259&siteid=1',
    'status' => '1',
  ),
  260 => 
  array (
    'catid' => '260',
    'parentid' => '252',
    'catname' => '成长历程',
    'siteid' => '1',
    'listorder' => '260',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=260&siteid=1',
    'status' => '1',
  ),
  261 => 
  array (
    'catid' => '261',
    'parentid' => '93',
    'catname' => '友情链接',
    'siteid' => '1',
    'listorder' => '261',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=261&siteid=1',
    'status' => '1',
  ),
  262 => 
  array (
    'catid' => '262',
    'parentid' => '252',
    'catname' => '支部简介',
    'siteid' => '1',
    'listorder' => '262',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=262&siteid=1',
    'status' => '1',
  ),
  266 => 
  array (
    'catid' => '266',
    'parentid' => '128',
    'catname' => '工程设计',
    'siteid' => '1',
    'listorder' => '266',
    'type' => '1',
    'url' => 'http://www.zxlh.asia/index.php?m=mobile&a=page&catid=266&siteid=1',
    'status' => '1',
  ),
);
?>